version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Mysecret312
      POSTGRES_USER: admin_user
      POSTGRES_DB: NTMO_database
    ports:
      - "5438:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql+psycopg2://admin_user:Mysecret312@postgres:5432/NTMO_database
      BOT_TOKEN: 1808395536:AAGSANn7Cfo6WOFxwbC_LjI6STiSUVVqSR0
      IP: localhost
      ADMINS: 765135326
      ADMIN_M1: 765135326
      ADMIN_M2: 765135326
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - ./telegram_volumes:/var/lib/backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
  pg_admin:
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin_password
      ports:
        - "5050:80"
      networks:
        - app_network
      deploy:
        resources:
          limits:
            cpus: "1"
            memory: 200M

networks:
  app_network:
    driver: bridge

#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: 10000M

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: [ "sh", "-c", "python -m uvicorn main:app --reload --host 0.0.0.0 --port 8001" ]
#    ports:
#      - "8001:8000"
##    environment:
##      DATABASE_URL: postgresql+psycopg2://admin_user:Mysecret312@postgres:5432/NTMO_database
##      BOT_TOKEN: 1808395536:AAGSANn7Cfo6WOFxwbC_LjI6STiSUVVqSR0
##      IP: localhost
##      ADMINS: 765135326
##      ADMIN_M1: 765135326
##      ADMIN_M2: 765135326
#    depends_on:
#      - postgres
#    networks:
#      - app_network
#    volumes:
#      - ./backend_volumes:/var/lib/backend


#
#  backend_migrate:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    environment:
#      DATABASE_URL: postgresql+psycopg2://admin_user:password@postgres:5432/symptomatologic
#    command: [ "sh", "-c", "python -m main.migrate migrate" ]
#    depends_on:
#      - postgres
#    networks:
#      - app_network

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    restart: always
#    env_file:
#      - frontend/.env
#    ports:
#      - "3000:3000"
#    environment:
#      - REACT_APP_API_URL= http://127.0.0.1:8000
#    depends_on:
#      - backend
#    networks:
#      - app_network
#    volumes:
#      - ./frontend_volumes:/var/lib/frontend:100M
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: 1200M
#  pg_admin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin_password
#    ports:
#      - "5050:80"
#    networks:
#      - app_network
#    deploy:
#      resources:
#        limits:
#          cpus: "1"
#          memory: 200M